# Generated by Django 4.1.2 on 2022-11-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='prduct',
            new_name='product',
        ),
    ]
